server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/code_generator # jdbc:mysql://<你的MySQL Host, 通常是localhost>:<你的MySQL端口, 通常3306>
    username: root # <你的MySQL账号, 请保证有足够的权限>
    password: root # <你的MySQL密码>
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
